site_name: 郭奕信 Kuo Yi Hsin
site_url: https://kuoyihs.in/
theme:
    name: 'material'
    language: zh-TW
    features:
      - navigation.tabs
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  # - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true
       # 讓中文 hyperlink 可正常顯示
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

plugins:
  - roamlinks
  - redirects:
      redirect_maps:
          'introvert-doing-customer-interview.md': 'https://kuoyihs.in/essays/introvert-advantages-in-product-development'
  - tags:
      tags_file: tags.md
  # 調整 nav 呈現
  - awesome-pages
